name: Release
on:
  push:
    tags:
      - '[0-9].[0-9]+.[0-9]+'

jobs:
    publish:
      name: Publish to PyPi
      # needs: check
      if: github.repository_owner == 'x-as-code' && github.repository == 'sphinx-ifelse'
      runs-on: ubuntu-latest
      steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install flit
        run: pip install flit~=3.4
      - name: Build and publish
        run: flit publish
        env:
          FLIT_USERNAME: __token__
          FLIT_PASSWORD: ${{ secrets.PYPI }}
